/* GENERATED by scripts/fetch_occasion_images.py — do not edit.
 *
 * The `.<hash>.` in each filename is a CONTENT HASH. next/image caches
 * by source url for four hours, so a photo replaced in place stays
 * invisible until that expires. It has to be the FILENAME and not a
 * `?v=` query: next/image answers 400 `"url" parameter is not allowed`
 * for a local path carrying a query string. */
export const OCCASION_IMAGES: Record<string, string> = {
  baby_shower: "/occasions/baby_shower.026e16b3.jpg",
  black_tie_event: "/occasions/black_tie_event.63d87089.jpg",
  brunch: "/occasions/brunch.71da676a.jpg",
  casual_outing: "/occasions/casual_outing.70143707.jpg",
  client_meeting: "/occasions/client_meeting.118daf74.jpg",
  conference: "/occasions/conference.86c23c51.jpg",
  dinner_date: "/occasions/dinner_date.e72174d3.jpg",
  engagement: "/occasions/engagement.41778932.jpg",
  festival_day: "/occasions/festival_day.9c6259a9.jpg",
  funeral: "/occasions/funeral.6b8d877c.jpg",
  graduation: "/occasions/graduation.2f4e1250.jpg",
  griha_pravesh: "/occasions/griha_pravesh.d8973552.jpg",
  haldi: "/occasions/haldi.f3607845.jpg",
  interview: "/occasions/interview.c3da56d8.jpg",
  mehendi: "/occasions/mehendi.6f0a2fe4.jpg",
  networking_event: "/occasions/networking_event.d4549710.jpg",
  office_casual: "/occasions/office_casual.6d169f1a.jpg",
  office_formal: "/occasions/office_formal.733bc974.jpg",
  office_party: "/occasions/office_party.f341bea1.jpg",
  party_night: "/occasions/party_night.46379488.jpg",
  sangeet: "/occasions/sangeet.c1c0711b.jpg",
  team_offsite: "/occasions/team_offsite.985bd755.jpg",
  temple_visit: "/occasions/temple_visit.a5ed6e3b.jpg",
  travel_day: "/occasions/travel_day.d801e63b.jpg",
  wedding_ceremony: "/occasions/wedding_ceremony.fb51a94c.jpg",
  wedding_reception: "/occasions/wedding_reception.c125d828.jpg",
  wfh: "/occasions/wfh.89f41f4c.jpg",
  workout: "/occasions/workout.d6dab76d.jpg",
};
