/* GENERATED by scripts/fetch_occasion_images.py — do not edit.
 *
 * The `.<hash>.` in each filename is a CONTENT HASH. next/image caches
 * by source url for four hours, so a photo replaced in place stays
 * invisible until that expires. It has to be the FILENAME and not a
 * `?v=` query: next/image answers 400 `"url" parameter is not allowed`
 * for a local path carrying a query string. */
export const OCCASION_IMAGES: Record<string, string> = {
  casual_outing: "/occasions/casual_outing.70143707.jpg",
  dinner_date: "/occasions/dinner_date.e72174d3.jpg",
  festival_day: "/occasions/festival_day.9c6259a9.jpg",
  interview: "/occasions/interview.c3da56d8.jpg",
  mehendi: "/occasions/mehendi.6f0a2fe4.jpg",
  office_casual: "/occasions/office_casual.6d169f1a.jpg",
  party_night: "/occasions/party_night.46379488.jpg",
  sangeet: "/occasions/sangeet.c1c0711b.jpg",
  temple_visit: "/occasions/temple_visit.a5ed6e3b.jpg",
  travel_day: "/occasions/travel_day.d801e63b.jpg",
  wedding_ceremony: "/occasions/wedding_ceremony.fb51a94c.jpg",
  workout: "/occasions/workout.d6dab76d.jpg",
};
