"""Everything each model produced for a garment, in one call (model QA).

WHY THIS EXISTS SEPARATELY FROM /garments/{id}/detail
-----------------------------------------------------
`detail` answers "what should the correction form show for this one garment".
This answers "is the model any good", which is a question about MANY garments
at once and needs the fields side by side with their confidences. Fetching
`detail` per garment to build that view is N+1 requests for a page of 50.

IT MUST SAY WHERE THE TAGS CAME FROM
------------------------------------
The single most misleading thing this project can show is a confident tag that
no model produced. There are three sources in this database right now and they
look identical in the UI:

  tag-vlm-v2     the real tag stage on Gemini — but possibly via the MOCK
                 model, which answers "kurta" for everything
  tag-vlm-v1     the same stage on the previous provider; kept distinct because
                 mixing providers in one eval measures neither
  seed-demo-v1   generated by scripts/seed_demo.py from weighted random draws
  NULL           tagged before the extractor_version collision was fixed

So every row carries `tag_source`, and a mock-derived tag is labelled as such.
Judging model quality on generated tags measures the generator, and that
mistake is very easy to make by looking at a pretty grid.
"""

from __future__ import annotations

from typing import Annotated, Any

from fastapi import APIRouter, Query
from sqlalchemy import text

from stylist_api.deps import CurrentUser, ObjectStoreDep, TenantDB
from stylist_domain.taxonomy import load_taxonomy

router = APIRouter(tags=["eval"])

# Fields the VLM is asked for, in the order a human reviews them.
TAG_FIELDS = (
    "slot",
    "subcategory",
    "primary_colour",
    "secondary_colour",
    "pattern",
    "material",
    "fit",
    "dress_code",
    "formality",
    "warmth",
)

# Tag versions that did NOT come from a real model call.
SYNTHETIC_VERSIONS = {"seed-demo-v1"}


def _tag_source(extractor_version: str | None, vlm_model: str | None) -> str:
    if extractor_version in SYNTHETIC_VERSIONS:
        return "synthetic (seed script — NOT model output)"
    if extractor_version is None:
        return "unknown (pre-dates the extractor_version fix)"
    if vlm_model and "mock" in vlm_model:
        return f"mock model ({vlm_model}) — deterministic stand-in, not a real VLM"
    return f"model ({vlm_model or extractor_version})"


@router.get("/garments/eval")
async def eval_view(
    user: CurrentUser,
    db: TenantDB,
    store: ObjectStoreDep,
    limit: Annotated[int, Query(ge=1, le=100)] = 24,
    offset: Annotated[int, Query(ge=0)] = 0,
    only_real: Annotated[bool, Query()] = False,
) -> dict[str, Any]:
    """A page of garments with every model output and its confidence.

    `only_real` filters to garments whose tags came from a real model call —
    the default is False so the view shows what is actually there, including
    the synthetic rows, clearly labelled.
    """
    from stylist_api.settings import get_settings

    vlm_model = get_settings().vlm_model
    taxonomy = load_taxonomy()
    review_below = {name: cfg.get("review_below") for name, cfg in taxonomy.fields.items()}

    where = ["is_active", "state NOT IN ('rejected', 'quarantined')"]
    if only_real:
        where.append("extractor_version IS NOT NULL")
        where.append("extractor_version <> ALL(:synthetic)")

    params: dict[str, Any] = {"lim": limit, "off": offset}
    if only_real:
        params["synthetic"] = list(SYNTHETIC_VERSIONS)

    rows = await db.execute(
        text(
            f"""
            SELECT id, original_key, cutout_key,
                   slot::text AS slot, subcategory::text AS subcategory,
                   primary_colour::text AS primary_colour,
                   secondary_colour::text AS secondary_colour,
                   pattern::text AS pattern, material::text AS material,
                   fit::text AS fit, dress_code::text AS dress_code,
                   formality, warmth, climate_bands,
                   field_confidence, user_verified_fields, needs_review,
                   extractor_version, embedding_version, state,
                   moderation, phash, duplicate_of,
                   (embedding IS NOT NULL) AS has_embedding,
                   attributes_raw->'tag'->>'degraded' AS tag_degraded,
                   attributes_raw->'tag'->>'reason' AS tag_reason,
                   created_at
            FROM garments
            WHERE {" AND ".join(where)}
            ORDER BY created_at DESC
            LIMIT :lim OFFSET :off
            """
        ),
        params,
    )

    items = []
    for r in rows.mappings():
        confidence = r["field_confidence"] or {}
        verified = set(r["user_verified_fields"] or [])
        fields = []
        for name in TAG_FIELDS:
            conf = confidence.get(name)
            threshold = review_below.get(name)
            fields.append(
                {
                    "field": name,
                    "value": r[name],
                    "confidence": float(conf) if conf is not None else None,
                    "review_below": threshold,
                    # Below threshold is why the garment is flagged; showing the
                    # number without the comparison makes the flag look arbitrary.
                    "below_threshold": (
                        conf is not None and threshold is not None and float(conf) < threshold
                    ),
                    # A user-corrected field is ground truth, not a prediction,
                    # and must not be counted when judging the model.
                    "user_verified": name in verified,
                }
            )
        items.append(
            {
                "id": str(r["id"]),
                "created_at": r["created_at"].isoformat(),
                "state": r["state"],
                "needs_review": r["needs_review"],
                "cutout_url": store.presign_download(r["cutout_key"]) if r["cutout_key"] else None,
                "original_url": (
                    store.presign_download(r["original_key"]) if r["original_key"] else None
                ),
                "fields": fields,
                "climate_bands": list(r["climate_bands"] or []),
                "tag_source": _tag_source(r["extractor_version"], vlm_model),
                "tag_is_real": (
                    r["extractor_version"] is not None
                    and r["extractor_version"] not in SYNTHETIC_VERSIONS
                    and not (vlm_model and "mock" in vlm_model)
                ),
                "tag_degraded": r["tag_degraded"] == "true",
                "tag_reason": r["tag_reason"],
                "extractor_version": r["extractor_version"],
                "embedding_version": r["embedding_version"],
                "has_embedding": bool(r["has_embedding"]),
                "phash": r["phash"],
                "duplicate_of": str(r["duplicate_of"]) if r["duplicate_of"] else None,
                "moderation": r["moderation"] or {},
            }
        )

    total = await db.execute(
        text(f"SELECT count(*) FROM garments WHERE {' AND '.join(where)}"),
        {k: v for k, v in params.items() if k not in ("lim", "off")},
    )
    # WHAT ACTUALLY TAGGED, not what config says. `vlm_model` is the API's own
    # setting, and the API does not tag — the worker does. When the two drifted
    # (the API missing VLM_MODEL while the worker had it) this page warned that
    # tagging was a stand-in while real Gemini was running, which is the worst
    # direction for a warning to be wrong in: it teaches people to distrust
    # correct output.
    #
    # `model_calls` is the record of calls that were actually made, so it
    # answers the question the banner is really asking. Config is still
    # reported alongside it, because a DISAGREEMENT between the two is itself
    # worth seeing rather than silently resolving in favour of either.
    # EXPLICIT user_id, because `model_calls` IS NOT RLS-PROTECTED.
    #
    # Every other tenant table in this schema is ENABLE + FORCE ROW LEVEL
    # SECURITY; this one has no policy at all (verified: relrowsecurity = f).
    # So a query here that relied on RLS the way the rest of the codebase does
    # reads EVERY tenant's calls — which is how the first version of this
    # reported another tenant's model name on this tenant's page.
    #
    # The predicate is the fix for this endpoint. The missing policy is a
    # SEPARATE, pre-existing gap: `model_calls` carries user_id, job_id and
    # cost, and the Phase 5 ops aggregates go through SECURITY DEFINER
    # functions precisely because they expect to be reading past a policy that
    # turns out not to exist.
    last_call = await db.execute(
        text(
            "SELECT model_name FROM model_calls "
            "WHERE purpose = 'tag' AND user_id = CAST(:uid AS uuid) "
            "ORDER BY created_at DESC LIMIT 1"
        ),
        {"uid": str(user.id)},
    )
    used = last_call.scalar_one_or_none()

    return {
        "items": items,
        "total": int(total.scalar_one()),
        "limit": limit,
        "offset": offset,
        # Stated once at the top so the whole page can be read in context.
        "tagging_model": used or vlm_model,
        "tagging_model_configured": vlm_model,
        # None when nothing has been tagged yet: "we have not run" and "we ran
        # a mock" are different facts, and collapsing them into False would
        # tell a new user their tags are real before any exist.
        "tagging_is_mock": (("mock" in used) if used else None),
        "tagging_config_disagrees": bool(used and vlm_model and used != vlm_model),
    }
