"""Everything each model produced for a garment, in one call (model QA).

WHY THIS EXISTS SEPARATELY FROM /garments/{id}/detail
-----------------------------------------------------
`detail` answers "what should the correction form show for this one garment".
This answers "is the model any good", which is a question about MANY garments
at once and needs the fields side by side with their confidences. Fetching
`detail` per garment to build that view is N+1 requests for a page of 50.

IT MUST SAY WHERE THE TAGS CAME FROM
------------------------------------
The single most misleading thing this project can show is a confident tag that
no model produced. There are three sources in this database right now and they
look identical in the UI:

  tag-vlm-v2     the real tag stage on Gemini — but possibly via the MOCK
                 model, which answers "kurta" for everything
  tag-vlm-v1     the same stage on the previous provider; kept distinct because
                 mixing providers in one eval measures neither
  seed-demo-v1   generated by scripts/seed_demo.py from weighted random draws
  NULL           tagged before the extractor_version collision was fixed

So every row carries `tag_source`, and a mock-derived tag is labelled as such.
Judging model quality on generated tags measures the generator, and that
mistake is very easy to make by looking at a pretty grid.
"""

from __future__ import annotations

from collections import Counter
from typing import Annotated, Any

from fastapi import APIRouter, Query
from sqlalchemy import text

from stylist_api.deps import CurrentUser, ObjectStoreDep, TenantDB
from stylist_domain.taxonomy import load_taxonomy

router = APIRouter(tags=["eval"])

# Fields the VLM is asked for, in the order a human reviews them.
TAG_FIELDS = (
    "slot",
    "subcategory",
    "primary_colour",
    "secondary_colour",
    "pattern",
    "material",
    "fit",
    "dress_code",
    "formality",
    "warmth",
)

# Tag versions that did NOT come from a real model call.
SYNTHETIC_VERSIONS = {"seed-demo-v1"}


def _is_mock(model: str | None) -> bool:
    return bool(model and "mock" in model)


def _tag_source(extractor_version: str | None, tagged_by: str | None) -> str:
    """What produced THIS row's tags. `tagged_by` is the model_calls row for
    this garment, not the current setting.

    This used to take `vlm_model` — the model the API is configured for TODAY —
    and attribute every historical row to it. Swapping the config rewrote the
    past: three garments tagged by `vlm-tagger-mock` on 10 Sep rendered as
    "model (vlm-tagger-openrouter)", naming a model that had never seen them.
    The mock check was worse still: it asked whether the CONFIGURED model is a
    mock to decide whether an OLD row is mock, so switching away from the mock
    silently relabelled stand-in tags as real ones.

    The banner above this list was already fixed to read `model_calls` instead
    of config, with a comment explaining why. The per-row label was left
    reading config in the same function — and it is the more dangerous of the
    two, because the banner only says the two disagree while this asserts one
    specific model with no hedging.
    """
    if extractor_version in SYNTHETIC_VERSIONS:
        return "synthetic (seed script — NOT model output)"
    # `tagged_by` OUTRANKS a missing extractor_version. Three rows on this
    # account have extractor_version NULL and a recorded `vlm-tagger-mock`
    # call: "unknown, pre-dates the extractor_version fix" would throw away a
    # ledger entry that says exactly what produced them, and the honest label
    # for a mock row matters more than the honest label for an old one.
    if tagged_by is not None:
        if "mock" in tagged_by:
            return f"mock model ({tagged_by}) — deterministic stand-in, not a real VLM"
        return f"model ({tagged_by})"
    if extractor_version is None:
        return "unknown (pre-dates the extractor_version fix)"
    # Tagged, but no call recorded against the job — written before
    # `model_calls` existed, or a cache hit that skipped the ledger.
    return f"model (unrecorded; extractor {extractor_version})"


@router.get("/garments/eval")
async def eval_view(
    user: CurrentUser,
    db: TenantDB,
    store: ObjectStoreDep,
    limit: Annotated[int, Query(ge=1, le=100)] = 24,
    offset: Annotated[int, Query(ge=0)] = 0,
    only_real: Annotated[bool, Query()] = False,
) -> dict[str, Any]:
    """A page of garments with every model output and its confidence.

    `only_real` filters to garments whose tags came from a real model call —
    the default is False so the view shows what is actually there, including
    the synthetic rows, clearly labelled.
    """
    from stylist_api.settings import get_settings

    vlm_model = get_settings().vlm_model
    taxonomy = load_taxonomy()
    review_below = {name: cfg.get("review_below") for name, cfg in taxonomy.fields.items()}

    where = ["is_active", "state NOT IN ('rejected', 'quarantined')"]
    if only_real:
        where.append("extractor_version IS NOT NULL")
        where.append("extractor_version <> ALL(:synthetic)")

    params: dict[str, Any] = {"lim": limit, "off": offset, "uid": str(user.id)}
    if only_real:
        params["synthetic"] = list(SYNTHETIC_VERSIONS)

    rows = await db.execute(
        text(
            f"""
            SELECT id, original_key, cutout_key,
                   slot::text AS slot, subcategory::text AS subcategory,
                   primary_colour::text AS primary_colour,
                   secondary_colour::text AS secondary_colour,
                   pattern::text AS pattern, material::text AS material,
                   fit::text AS fit, dress_code::text AS dress_code,
                   formality, warmth, climate_bands,
                   field_confidence, user_verified_fields, needs_review,
                   extractor_version, embedding_version, state,
                   moderation, phash, duplicate_of,
                   (embedding IS NOT NULL) AS has_embedding,
                   attributes_raw->'tag'->>'degraded' AS tag_degraded,
                   attributes_raw->'tag'->>'reason' AS tag_reason,
                   created_at,
                   -- PER-ROW PROVENANCE. jobs.garment_id is the only link
                   -- between a garment and the call that tagged it, and it is
                   -- what makes this page able to say "this one is mock" about
                   -- a single row rather than about the whole page.
                   --
                   -- EXPLICIT user_id on model_calls: that table has NO RLS
                   -- policy (relrowsecurity = f), unlike `jobs` and every
                   -- other tenant table here. Without the predicate this
                   -- lateral reads other tenants' calls, which is the exact
                   -- bug the banner query below already carries a comment
                   -- about. `jobs` is RLS-scoped, so the join is belt and
                   -- braces on that side.
                   (SELECT mc.model_name
                      FROM jobs j
                      JOIN model_calls mc ON mc.job_id = j.id
                     WHERE j.garment_id = garments.id
                       AND mc.purpose = 'tag'
                       AND mc.user_id = CAST(:uid AS uuid)
                     ORDER BY mc.created_at DESC
                     LIMIT 1) AS tagged_by
            FROM garments
            WHERE {" AND ".join(where)}
            ORDER BY created_at DESC
            LIMIT :lim OFFSET :off
            """
        ),
        params,
    )

    items = []
    for r in rows.mappings():
        confidence = r["field_confidence"] or {}
        verified = set(r["user_verified_fields"] or [])
        fields = []
        for name in TAG_FIELDS:
            conf = confidence.get(name)
            threshold = review_below.get(name)
            fields.append(
                {
                    "field": name,
                    "value": r[name],
                    "confidence": float(conf) if conf is not None else None,
                    "review_below": threshold,
                    # Below threshold is why the garment is flagged; showing the
                    # number without the comparison makes the flag look arbitrary.
                    "below_threshold": (
                        conf is not None and threshold is not None and float(conf) < threshold
                    ),
                    # A user-corrected field is ground truth, not a prediction,
                    # and must not be counted when judging the model.
                    "user_verified": name in verified,
                }
            )
        items.append(
            {
                "id": str(r["id"]),
                "created_at": r["created_at"].isoformat(),
                "state": r["state"],
                "needs_review": r["needs_review"],
                "cutout_url": store.presign_download(r["cutout_key"]) if r["cutout_key"] else None,
                "original_url": (
                    store.presign_download(r["original_key"]) if r["original_key"] else None
                ),
                "fields": fields,
                "climate_bands": list(r["climate_bands"] or []),
                "tag_source": _tag_source(r["extractor_version"], r["tagged_by"]),
                "tagged_by": r["tagged_by"],
                # This row's own model, not the configured one. Switching away
                # from the mock must not retroactively promote rows the mock
                # produced. A recorded call is the strongest evidence there is,
                # so it decides on its own; extractor_version is the fallback
                # for rows older than the ledger.
                "tag_is_real": (
                    (not _is_mock(r["tagged_by"]))
                    if r["tagged_by"] is not None
                    else (
                        r["extractor_version"] is not None
                        and r["extractor_version"] not in SYNTHETIC_VERSIONS
                    )
                ),
                "tag_degraded": r["tag_degraded"] == "true",
                "tag_reason": r["tag_reason"],
                "extractor_version": r["extractor_version"],
                "embedding_version": r["embedding_version"],
                "has_embedding": bool(r["has_embedding"]),
                "phash": r["phash"],
                "duplicate_of": str(r["duplicate_of"]) if r["duplicate_of"] else None,
                "moderation": r["moderation"] or {},
            }
        )

    total = await db.execute(
        text(f"SELECT count(*) FROM garments WHERE {' AND '.join(where)}"),
        {k: v for k, v in params.items() if k not in ("lim", "off")},
    )
    # WHAT ACTUALLY TAGGED, not what config says. `vlm_model` is the API's own
    # setting, and the API does not tag — the worker does. When the two drifted
    # (the API missing VLM_MODEL while the worker had it) this page warned that
    # tagging was a stand-in while real Gemini was running, which is the worst
    # direction for a warning to be wrong in: it teaches people to distrust
    # correct output.
    #
    # `model_calls` is the record of calls that were actually made, so it
    # answers the question the banner is really asking. Config is still
    # reported alongside it, because a DISAGREEMENT between the two is itself
    # worth seeing rather than silently resolving in favour of either.
    # EXPLICIT user_id, because `model_calls` IS NOT RLS-PROTECTED.
    #
    # Every other tenant table in this schema is ENABLE + FORCE ROW LEVEL
    # SECURITY; this one has no policy at all (verified: relrowsecurity = f).
    # So a query here that relied on RLS the way the rest of the codebase does
    # reads EVERY tenant's calls — which is how the first version of this
    # reported another tenant's model name on this tenant's page.
    #
    # The predicate is the fix for this endpoint. The missing policy is a
    # SEPARATE, pre-existing gap: `model_calls` carries user_id, job_id and
    # cost, and the Phase 5 ops aggregates go through SECURITY DEFINER
    # functions precisely because they expect to be reading past a policy that
    # turns out not to exist.
    last_call = await db.execute(
        text(
            "SELECT model_name FROM model_calls "
            "WHERE purpose = 'tag' AND user_id = CAST(:uid AS uuid) "
            "ORDER BY created_at DESC LIMIT 1"
        ),
        {"uid": str(user.id)},
    )
    used = last_call.scalar_one_or_none()

    # WHAT IS ACTUALLY ON THIS PAGE, per model. The banner used to say "tags
    # below were produced by <the last call's model>", which is only true if
    # every row came from one model. On this account it was five from
    # `vlm-tagger`, three from `vlm-tagger-mock` and one unrecorded — so the
    # sentence was wrong about four of nine rows, and wrong in the direction
    # that hides mock output.
    #
    # A page-level summary cannot answer a per-row question. It can report the
    # distribution, which is a question it CAN answer, and the per-row label
    # carries the rest.
    on_page = Counter(str(i["tagged_by"] or "unrecorded") for i in items)

    return {
        "items": items,
        "total": int(total.scalar_one()),
        "limit": limit,
        "offset": offset,
        # Stated once at the top so the whole page can be read in context.
        "tagging_model": used or vlm_model,
        "tagging_model_configured": vlm_model,
        # Ordered most-common first so the UI can render it as written.
        "tagging_models_on_page": [
            {"model": name, "garments": n} for name, n in on_page.most_common()
        ],
        "tagging_mixed_on_page": len(on_page) > 1,
        # None when nothing has been tagged yet: "we have not run" and "we ran
        # a mock" are different facts, and collapsing them into False would
        # tell a new user their tags are real before any exist.
        "tagging_is_mock": (("mock" in used) if used else None),
        "tagging_config_disagrees": bool(used and vlm_model and used != vlm_model),
    }
