"""Fetch the occasion tile photographs from Unsplash.

WHY A SCRIPT AND NOT A RUNTIME CALL
-----------------------------------
Twelve tiles that never change do not need a third party on the request path.
This runs once, writes `web/public/occasions/<taxonomy id>.jpg`, and the app
serves static files with no key, no rate limit and no outage to degrade around.

WHY UNSPLASH AND NOT THE FREE-SEARCH SOURCES
--------------------------------------------
Wikimedia Commons and Openverse were tried first and are the wrong shape for
this. Commons has documentary photography — its best match for `travel_day`
was an empty airport walkway and for `festival_day` a firework in a farmyard,
both accurate and both useless on a tile advertising CLOTHES. Openverse's
fashion content skews to runway and glamour, much of it framed in ways that do
not belong on a product surface. Unsplash is editorial fashion photography,
which is the actual subject matter here.

ATTRIBUTION IS WRITTEN BY THIS SCRIPT, NOT BY HAND
--------------------------------------------------
The Unsplash API returns the photographer's name and profile link, and their
guidelines require both. The previous credits file was hand-written from
memory and had TODO in half its cells; this generates CREDITS.md from the API
response, so it cannot drift from what was actually downloaded.

It also pings each photo's `download_location`, which is an explicit API
guideline — that endpoint is how a photographer's download count is credited.
Skipping it costs nothing technically and is the difference between using the
API as intended and taking from it.

    UNSPLASH_ACCESS_KEY=... python scripts/fetch_occasion_images.py [--dry-run]

The key is read from the environment or from `.env`; it is never printed.
"""

from __future__ import annotations

import argparse
import contextlib
import os
import pathlib
import re
import sys
import time

import httpx
from PIL import Image

API = "https://api.unsplash.com"
OUT = pathlib.Path("web/public/occasions")

# One square size for every tile. The grid renders ~260px, so 520 covers 2x
# displays and nothing more.
SIDE = 520

# Crop from 18% DOWN, not the centre. On a full-length fashion photo the
# centre of the frame is the hem, so a square centre-crop of a person is a
# crop of their legs. Biasing upward keeps the garment and the face.
CROP_TOP_BIAS = 0.18

# Queries name the GARMENT and the person wearing it, never the venue. A tile
# for `temple_visit` wants a kurta, not a temple; the tile advertises clothes.
QUERIES: dict[str, str] = {
    "wedding_ceremony": "indian wedding lehenga outfit",
    "party_night": "party outfit night out fashion",
    "office_casual": "business casual workwear outfit",
    "dinner_date": "date night outfit fashion",
    "festival_day": "saree indian traditional outfit",
    "travel_day": "travel outfit street style",
    "casual_outing": "casual street style outfit",
    "interview": "formal suit interview outfit",
    "workout": "athletic wear tracksuit sportswear outfit",
    "mehendi": "mehendi haldi indian outfit yellow",
    "sangeet": "sangeet indian wedding outfit dance",
    "temple_visit": "kurta indian traditional menswear",
}


GENERATED_MAP = pathlib.Path("web/app/occasion-images.ts")


def _write_image_map() -> None:
    """Regenerate the occasion -> versioned URL map.

    THE FILENAME CARRIES THE HASH, AND IT HAS TO BE THE FILENAME.
    `next/image` serves these through `/_next/image?url=...` with
    `Cache-Control: max-age=14400` — four hours — keyed on the source path. A
    photo replaced in place is therefore invisible to anyone who loaded the
    page in the last four hours; measured exactly that after the first run.

    The obvious fix, `?v=<hash>` on the src, DOES NOT WORK: next/image rejects
    a query string on a local path with `"url" parameter is not allowed` (400),
    so every tile would have failed to load instead of being stale. Verified
    against the running server before this was written the second time.

    So the hash goes in the filename. A changed photo gets a new path and
    appears at once; an unchanged one keeps its path and stays cached.
    Generated, because a hash a human has to remember to update is a hash that
    will be wrong.
    """
    import hashlib

    lines = [
        "/* GENERATED by scripts/fetch_occasion_images.py — do not edit.",
        " *",
        " * The `.<hash>.` in each filename is a CONTENT HASH. next/image caches",
        " * by source url for four hours, so a photo replaced in place stays",
        " * invisible until that expires. It has to be the FILENAME and not a",
        " * `?v=` query: next/image answers 400 `\"url\" parameter is not allowed`",
        " * for a local path carrying a query string. */",
        "export const OCCASION_IMAGES: Record<string, string> = {",
    ]
    for f in sorted(OUT.glob("*.jpg")):
        occasion = f.stem.split(".")[0]
        digest = hashlib.sha256(f.read_bytes()).hexdigest()[:8]
        final = OUT / f"{occasion}.{digest}.jpg"
        if f != final:
            # Drop any previous hash for this occasion; only the current photo
            # should be reachable, and stale files would ship in the bundle.
            for old_file in OUT.glob(f"{occasion}.*.jpg"):
                if old_file != f:
                    old_file.unlink()
            f.rename(final)
        lines.append(f'  {occasion}: "/occasions/{final.name}",')
    lines.append("};")
    GENERATED_MAP.write_text("\n".join(lines) + "\n")
    print(f"  wrote {GENERATED_MAP}")


def read_key() -> str:
    key = os.environ.get("UNSPLASH_ACCESS_KEY", "").strip()
    if not key:
        env = pathlib.Path(".env")
        if env.exists():
            m = re.search(r"^UNSPLASH_ACCESS_KEY=(.+)$", env.read_text(), re.M)
            key = m.group(1).strip() if m else ""
    if not key:
        print("UNSPLASH_ACCESS_KEY is not set (env or .env)")
        raise SystemExit(1)
    return key


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="search and report; write nothing")
    ap.add_argument("--only", help="comma-separated taxonomy ids to refresh")
    args = ap.parse_args()

    key = read_key()
    headers = {"Authorization": f"Client-ID {key}", "Accept-Version": "v1"}
    wanted = set(args.only.split(",")) if args.only else set(QUERIES)
    if args.only:
        print("  note: --only cannot see the ids of tiles it is not refreshing,")
        print("  so a refreshed tile may duplicate an existing one. Check the sheet.")
    OUT.mkdir(parents=True, exist_ok=True)

    credits: list[tuple[str, str, str, str]] = []
    # THE SAME PHOTO CAN WIN TWO QUERIES. "casual street style outfit" and
    # "business casual workwear outfit" both returned the identical woman in a
    # white coat, and two identical tiles side by side read as a broken grid
    # rather than as a coincidence. Tracking the ids and walking down the
    # result list is cheaper than hand-picking every query until they diverge.
    used_ids: set[str] = set()
    for occasion, query in QUERIES.items():
        if occasion not in wanted:
            continue
        try:
            r = httpx.get(
                f"{API}/search/photos",
                params={
                    "query": query,
                    # More than one, so a collision with an earlier tile can be
                    # skipped rather than shipped.
                    "per_page": 8,
                    # Portrait: a person head-to-toe. A landscape crop of a
                    # standing figure throws away the outfit.
                    "orientation": "portrait",
                    "content_filter": "high",
                },
                headers=headers,
                timeout=40,
            )
            r.raise_for_status()
            hits = [h for h in (r.json().get("results") or []) if h["id"] not in used_ids]
            if not hits:
                print(f"  {occasion:18} no unused results for {query!r}")
                continue
            photo = hits[0]
            used_ids.add(photo["id"])

            if args.dry_run:
                print(f"  {occasion:18} {photo['id']}  by {photo['user']['name']}")
                continue

            img = httpx.get(photo["urls"]["regular"], timeout=60, follow_redirects=True)
            img.raise_for_status()
            path = OUT / f"{occasion}.jpg"
            path.write_bytes(img.content)

            with Image.open(path) as opened:
                rgb = opened.convert("RGB")
            w, h = rgb.size
            side = min(w, h)
            top = 0 if h <= w else int((h - side) * CROP_TOP_BIAS)
            left = (w - side) // 2
            square = rgb.crop((left, top, left + side, top + side))
            square.resize((SIDE, SIDE), Image.Resampling.LANCZOS).save(
                path, "JPEG", quality=80, optimize=True, progressive=True
            )

            # API guideline: this is how the photographer gets credited with
            # the download. It returns a url; hitting it is the whole point.
            with contextlib.suppress(Exception):
                httpx.get(photo["links"]["download_location"], headers=headers, timeout=20)

            credits.append(
                (
                    occasion,
                    photo["user"]["name"],
                    photo["user"]["links"]["html"],
                    photo["links"]["html"],
                )
            )
            kb = path.stat().st_size // 1024
            print(f"  {occasion:18} {kb:3d} KB  by {photo['user']['name']}")
            time.sleep(0.3)
        except Exception as exc:
            print(f"  {occasion:18} FAILED {type(exc).__name__}: {str(exc)[:70]}")

    if not args.dry_run:
        _write_image_map()

    if credits and not args.dry_run:
        lines = [
            "# Occasion tile photographs — attribution",
            "",
            "Generated by `scripts/fetch_occasion_images.py`. Do not edit by hand:",
            "a hand-written credits file drifts from what was actually downloaded,",
            "which is how the previous version ended up half TODO.",
            "",
            "Photographs from [Unsplash](https://unsplash.com), used under the",
            "[Unsplash License](https://unsplash.com/license). Attribution is not",
            "legally required by that licence but IS requested by it, and costs one",
            "table — so it is here.",
            "",
            "| occasion | photographer | photo |",
            "|---|---|---|",
        ]
        lines += [f"| {o} | [{n}]({u}) | [link]({p}) |" for o, n, u, p in sorted(credits)]
        (OUT / "CREDITS.md").write_text("\n".join(lines) + "\n")
        print(f"\n  wrote {OUT / 'CREDITS.md'} with {len(credits)} attributions")
    return 0


sys.exit(main())
