/**
 * Flat config, because `next lint` is gone.
 *
 * WHY THIS FILE EXISTS
 * --------------------
 * `package.json` carried `"lint": "next lint"` from the day the app was
 * scaffolded. Next 16 removed that command, and `next lint` now reads its
 * first argument as a project directory — so `npm run lint` was failing with
 * "no such directory: web/lint". There was also no eslint config of any kind
 * here, which means ESLint has never actually run over this app. Treat any
 * rule this turns up as pre-existing, not as a regression.
 *
 * `core-web-vitals` over the base config: it promotes the rules that affect
 * LCP/CLS from warning to error. This app renders a grid of garment photos,
 * which is exactly the workload those rules are about.
 */

import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/gen_firebase_sw.py from .env. Linting generated
    // output reports faults nobody can fix in the file they are editing.
    "public/firebase-messaging-sw.js",
  ]),
]);
